'use client';

/**
 * DemoAnnotatedReport — Container 3
 *
 * Browser-chrome container that renders the REAL WorkflowReportPage (via
 * next/dynamic ssr:false — it uses client hooks, scroll-spy, count-up) fed by
 * real engine snapshots generated by scripts/generate-demo-report-fixtures.ts.
 *
 * Numbered popups annotate the top-of-report sections (visible without scroll);
 * the rest of the report is fully explorable by scrolling inside the container.
 *
 * Hard constraints: 'use client', plain-JSON fixtures only (no server imports),
 * no Date.now()/Math.random(), additive (RealProductDemo + Containers 1/2 untouched).
 */

import dynamic from 'next/dynamic';
import DemoAnnotations, { type DemoAnnotation } from './DemoAnnotations';
import type { WorkflowReportPageProps } from '@/components/detail/WorkflowReportPage';

// Plain-JSON snapshots — no engine pipeline, no server modules.
/* eslint-disable @typescript-eslint/no-var-requires */
const reportWorkflow = require('./fixtures/demoReportWorkflow.json');
const reportProcessOutput = require('./fixtures/demoReportProcessOutput.json');
const reportInterpretation = require('./fixtures/demoReportInterpretation.json');
const reportInsights = require('./fixtures/demoReportInsights.json');
const reportIntelligence = require('./fixtures/demoReportIntelligence.json');
const reportAgentIntelligence = require('./fixtures/demoReportAgentIntelligence.json');
/* eslint-enable @typescript-eslint/no-var-requires */

const WorkflowReportPage = dynamic(
  () =>
    import('@/components/detail/WorkflowReportPage').then((m) => ({
      default: m.WorkflowReportPage,
    })),
  {
    ssr: false,
    loading: () => (
      <div className="flex h-full items-center justify-center text-[13px] text-[var(--content-secondary)]">
        Loading report…
      </div>
    ),
  },
);

const REPORT_ANNOTATIONS: DemoAnnotation[] = [
  {
    id: 'r1',
    number: 1,
    top: '14%',
    left: '26%',
    popoverSide: 'bottom',
    title: 'Process Summary',
    body: 'At a glance: step count, phases, systems, duration, and confidence — all from recorded runs. A quick read on complexity and how well the process is characterized.',
  },
  {
    id: 'r2',
    number: 2,
    top: '30%',
    left: '62%',
    popoverSide: 'left',
    title: 'Observed Verdict',
    body: '1–4 plain-English sentences describing what the runs actually show, with an evidence-linked badge. No benchmarks, no estimates.',
  },
  {
    id: 'r3',
    number: 3,
    top: '52%',
    left: '30%',
    popoverSide: 'top',
    title: 'Process Scorecard',
    body: 'Five KPIs in one row: Cycle Time, Consistency, Variant Count, top Bottleneck, and Automation Score — all from captured events.',
  },
  {
    id: 'r4',
    number: 4,
    top: '34%',
    left: '7%',
    popoverSide: 'right',
    title: 'Section navigation',
    body: 'The report runs deep — verdict, scorecard, timestudy, distribution, consistency, bottlenecks, automation, ROI, variants, drift, and agent intelligence. Jump to any section; it highlights as you scroll.',
  },
  {
    id: 'r5',
    number: 5,
    top: '72%',
    left: '58%',
    popoverSide: 'top',
    title: 'Health & scores',
    body: 'Complexity, Friction, Linearity, and Manual Intensity, each 0–100 with a label. Lower is better for Friction and Manual Intensity.',
  },
];

export default function DemoAnnotatedReport() {
  return (
    <div className="mx-auto w-full max-w-5xl overflow-hidden rounded-xl border border-[var(--border-default)] bg-[var(--surface-elevated)] shadow-2xl">
      {/* Browser chrome */}
      <div className="flex items-center gap-3 border-b border-[var(--border-subtle)] bg-[var(--surface-secondary)] px-4 py-2.5">
        <div className="flex gap-1.5">
          <span className="h-3 w-3 rounded-full bg-red-400/80" />
          <span className="h-3 w-3 rounded-full bg-amber-400/80" />
          <span className="h-3 w-3 rounded-full bg-green-400/80" />
        </div>
        <div className="flex flex-1 items-center justify-center">
          <div className="flex items-center gap-1.5 rounded-md border border-[var(--border-subtle)] bg-[var(--surface-primary)] px-3 py-1 text-[12px] text-[var(--content-secondary)] max-w-sm w-full">
            <svg aria-hidden className="h-3 w-3 shrink-0 opacity-50" viewBox="0 0 16 16" fill="currentColor">
              <path fillRule="evenodd" d="M8 0a8 8 0 100 16A8 8 0 008 0zm0 1.5a6.5 6.5 0 110 13 6.5 6.5 0 010-13z" clipRule="evenodd" />
            </svg>
            app.ledgerium.ai/workflows/approve-expense-report/report
          </div>
        </div>
        <span className="shrink-0 rounded-full border border-amber-500/25 bg-amber-500/15 px-2.5 py-0.5 text-[11px] font-medium text-amber-400">
          Sample data
        </span>
      </div>

      {/* Annotated, internally-scrolling report */}
      <DemoAnnotations annotations={REPORT_ANNOTATIONS}>
        <div className="overflow-y-auto bg-[var(--surface-primary)]" style={{ height: 580 }}>
          <WorkflowReportPage
            workflow={reportWorkflow as WorkflowReportPageProps['workflow']}
            insights={reportInsights as WorkflowReportPageProps['insights']}
            interpretation={reportInterpretation as WorkflowReportPageProps['interpretation']}
            intelligence={reportIntelligence as WorkflowReportPageProps['intelligence']}
            agentIntelligence={reportAgentIntelligence as WorkflowReportPageProps['agentIntelligence']}
            processOutput={reportProcessOutput as WorkflowReportPageProps['processOutput']}
          />
        </div>
      </DemoAnnotations>
    </div>
  );
}
