/**
 * Step Label Humanization — Shared Content Quality Layer
 *
 * Transforms weak technical step labels into clear, human-readable text
 * suitable for SOP documents, workflow diagrams, and process maps.
 *
 * Strategy:
 * 1. Detect whether the title is already good (specific, imperative, 3+ words)
 * 2. If weak, mine available context: instructions, target labels, system,
 *    page title, action type, step sequence
 * 3. Build the clearest possible label from available signals
 * 4. Never fabricate — only use data that's actually present
 * 5. Fall back to a structured but honest label when nothing better exists
 *
 * Used by: sop-view/adapters/sopViewModel.ts, workflow-view/adapters/viewModel.ts
 */

// ─── Weak label patterns ─────────────────────────────────────────────────────
// These are generated by the segmentation engine and SOP builder when DOM
// elements lack semantic labels. We detect them and replace with better text.

const WEAK_TITLES = new Set([
  'perform action',
  'click element',
  'update field',
  'enter field',
  'interact with page',
  'complete action',
  'handle error',
  'attach file',
  'navigation step',
  'action step',
  'action',
  'navigation',
  'form submit',
  'data entry',
  'send / submit',
  'file action',
  'error handling',
  'repeated action',
  'annotation',
]);

/** Prefixes that indicate a generic fallback from the engine. */
const WEAK_PREFIXES = [
  'Click the target element',
  'Click element on',
  'Click element in',
  'Enter the required value',
  'Enter field on',
  'Enter field in',
  'Update field on',
  'Update field in',
  'Interact with page',
  'Interact with',
  'Complete action on',
  'Complete action in',
  'Perform action',
  'Navigation on',
  'Action on',
  'Action in',
  'Form Submit on',
  'Data Entry on',
];

/** Words that are just raw HTML tags — should never appear in labels. */
const RAW_HTML_TAGS = new Set([
  'div', 'span', 'svg', 'input', 'button', 'a', 'p', 'li', 'ul', 'ol',
  'section', 'article', 'main', 'header', 'footer', 'nav', 'form', 'fieldset',
  'textarea', 'select', 'img', 'figure', 'table', 'tr', 'td', 'th',
]);

// ─── Instruction context ─────────────────────────────────────────────────────

export interface InstructionContext {
  text: string;
  type: 'action' | 'wait' | 'verify' | 'note' | string;
  system: string;
  targetLabel: string;
  isSensitive: boolean;
}

// ─── Main humanization function ──────────────────────────────────────────────

/**
 * Produce a human-readable step label from available context.
 *
 * Priority order:
 * 1. If title is already good (specific, 3+ words, imperative verb) → keep
 * 2. If instructions have a clear first action with a target label → use it
 * 3. If action text is different and richer than title → use it
 * 4. If system + page context available → build structured label
 * 5. Last resort → "Step N: {category}" (never empty, never bare HTML)
 */
export function humanizeStepLabel(params: {
  rawTitle: string;
  category: string;
  categoryLabel: string;
  system?: string | undefined;
  action?: string | undefined;
  pageTitle?: string | undefined;
  routeTemplate?: string | undefined;
  instructions?: InstructionContext[];
  ordinal?: number | undefined;
}): string {
  const {
    rawTitle,
    category,
    categoryLabel,
    system,
    action,
    pageTitle,
    routeTemplate,
    instructions = [],
    ordinal,
  } = params;

  const title = clean(rawTitle);

  // ── Step 1: Is the title already good? ───────────────────────────────────

  if (title && isGoodTitle(title)) return title;

  // ── Step 2: Try the action field (often richer than title) ───────────────

  if (action) {
    const cleanAction = clean(action);
    if (cleanAction && isGoodTitle(cleanAction) && cleanAction !== title) {
      return cleanAction;
    }
  }

  // ── Step 3: Mine instructions for a clear first-action label ─────────────

  const fromInstructions = extractLabelFromInstructions(instructions, categoryLabel);
  if (fromInstructions) return fromInstructions;

  // ── Step 4: Build from title + context enrichment ────────────────────────

  if (title && !isWeakTitle(title)) {
    // Title exists and isn't explicitly weak — just short. Add context.
    return enrichShortTitle(title, system, pageTitle);
  }

  // ── Step 5: Build from context alone ─────────────────────────────────────

  return buildContextLabel(categoryLabel, system, pageTitle, routeTemplate, ordinal);
}

/**
 * Produce a short label (max ~35 chars) for compact displays like diagram
 * nodes and step rail buttons. Derived from the full label.
 */
export function humanizeShortLabel(fullLabel: string, maxLen: number = 35): string {
  if (fullLabel.length <= maxLen) return fullLabel;

  // Try to truncate at a word boundary
  const truncated = fullLabel.slice(0, maxLen);
  const lastSpace = truncated.lastIndexOf(' ');
  if (lastSpace > maxLen * 0.6) {
    return truncated.slice(0, lastSpace) + '…';
  }
  return truncated.slice(0, maxLen - 1) + '…';
}

/**
 * Improve instruction text for SOP procedure display. Cleans up generic
 * instruction phrases while preserving specific ones.
 */
export function humanizeInstructionText(text: string, targetLabel: string, system: string): string {
  let cleaned = clean(text);
  if (!cleaned) return '';

  // Replace generic "Click the target element" with something better
  if (cleaned === 'Click the target element' || cleaned === 'Click the target element on ""') {
    if (targetLabel) return `Click "${targetLabel}"`;
    if (system) return `Click the required element in ${system}`;
    return 'Click the indicated element';
  }

  // Replace "Enter the required value" with field context
  if (cleaned === 'Enter the required value' || cleaned.startsWith('Enter the required value on ""')) {
    if (targetLabel) return `Enter value in "${targetLabel}"`;
    if (system) return `Enter the required value in ${system}`;
    return 'Enter the required value';
  }

  // Clean up empty quoted strings like 'Click ""' → 'Click the element'
  cleaned = cleaned.replace(/""\s*/g, '').replace(/\s+/g, ' ').trim();

  return cleaned;
}

// ─── Internal helpers ────────────────────────────────────────────────────────

function clean(s: string | undefined | null): string {
  if (!s) return '';
  return s.trim().replace(/\s+/g, ' ');
}

/** A title is "good" if it has 3+ words and starts with an imperative verb. */
function isGoodTitle(title: string): boolean {
  const words = title.split(/\s+/);
  if (words.length < 3) return false;

  // Check it's not a weak pattern despite being 3+ words
  const lower = title.toLowerCase();
  if (WEAK_PREFIXES.some(p => lower.startsWith(p.toLowerCase()))) return false;

  // Check first word isn't a raw HTML tag
  if (RAW_HTML_TAGS.has(words[0]!.toLowerCase())) return false;

  return true;
}

/** A title is "weak" if it matches known generic patterns. */
function isWeakTitle(title: string): boolean {
  const lower = title.toLowerCase().trim();
  if (WEAK_TITLES.has(lower)) return true;
  if (WEAK_PREFIXES.some(p => lower.startsWith(p.toLowerCase()))) return true;
  // Single word that's just a category name
  if (lower.split(/\s+/).length === 1 && WEAK_TITLES.has(lower)) return true;
  return false;
}

/**
 * Extract the best label from the instruction array.
 * Looks for the first action instruction with a useful target label or
 * concise text that's better than the step title.
 */
function extractLabelFromInstructions(
  instructions: InstructionContext[],
  categoryLabel: string,
): string | null {
  if (instructions.length === 0) return null;

  // Priority 1: Action instruction with a target label (e.g., 'Click "Submit"')
  for (const inst of instructions) {
    if (inst.type !== 'action') continue;
    if (inst.targetLabel && !RAW_HTML_TAGS.has(inst.targetLabel.toLowerCase())) {
      // Build a nice label: 'Click "Submit"' or 'Enter value in "Email"'
      const text = clean(inst.text);
      if (text && !isWeakTitle(text) && text.includes('"') && text.length <= 50) {
        return text;
      }
      // If the instruction text is weak, build from target label
      return `${categoryLabel}: ${inst.targetLabel}`;
    }
  }

  // Priority 2: First action instruction text that's concise and specific
  for (const inst of instructions) {
    if (inst.type !== 'action') continue;
    const text = clean(inst.text);
    if (!text) continue;
    if (isWeakTitle(text)) continue;

    // Text is specific and short enough for a label
    if (text.length <= 45 && text.split(/\s+/).length >= 2) {
      return text;
    }
    // Text is too long — take the first meaningful clause
    if (text.length > 45) {
      // Try to find a natural break point
      const dash = text.indexOf(' — ');
      if (dash > 10 && dash < 45) return text.slice(0, dash);
      const paren = text.indexOf(' (');
      if (paren > 10 && paren < 45) return text.slice(0, paren);
      return text.slice(0, 43) + '…';
    }
  }

  // Priority 3: Verify instruction (e.g., "Verify confirmation appears")
  const verify = instructions.find(i => i.type === 'verify');
  if (verify) {
    const text = clean(verify.text);
    if (text && !isWeakTitle(text) && text.length <= 50) {
      return text;
    }
  }

  return null;
}

/** Add context to a short but non-weak title. */
function enrichShortTitle(title: string, system?: string, pageTitle?: string): string {
  // "Submit" → "Submit in Gmail"
  if (system && !title.toLowerCase().includes(system.toLowerCase())) {
    return `${title} in ${system}`;
  }
  // "Submit" → "Submit on Invoice Page"
  if (pageTitle && !title.toLowerCase().includes(pageTitle.toLowerCase())) {
    return `${title} on ${pageTitle}`;
  }
  return title;
}

/** Build a label purely from context when no usable title exists. */
function buildContextLabel(
  categoryLabel: string,
  system?: string,
  pageTitle?: string,
  routeTemplate?: string,
  ordinal?: number,
): string {
  // Best: page title + system
  if (pageTitle && system && pageTitle !== system) {
    return `${categoryLabel} on ${pageTitle} (${system})`;
  }
  if (pageTitle) return `${categoryLabel} on ${pageTitle}`;
  if (system && routeTemplate) return `${categoryLabel} at ${routeTemplate} (${system})`;
  if (system) return `${categoryLabel} in ${system}`;
  if (routeTemplate) return `${categoryLabel} at ${routeTemplate}`;
  // Absolute last resort — ordinal-tagged
  if (ordinal !== undefined) return `${categoryLabel} — step ${ordinal}`;
  return `${categoryLabel}`;
}
