/**
 * Markdown renderer — converts structured template artifacts into clean,
 * export-ready Markdown documents.
 *
 * Produces consultant-grade Markdown for all 6 template types.
 * All renderers are pure and deterministic.
 */

import type {
  RenderedProcessMap,
  SwimlaneProcessMap,
  BPMNProcessMap,
  SIPOCProcessMap,
  RenderedSOP,
  OperatorSOP,
  EnterpriseSOP,
  DecisionSOP,
} from '../templateTypes.js';
import { mdHeading, mdBullet, mdNumbered, mdBold, mdTable, mdCallout } from './renderHelpers.js';

// ─── Document frame ──────────────────────────────────────────────────────────

function documentFooter(meta?: { stepCount?: number; confidence?: number; generatedAt?: string }): string {
  const parts: string[] = ['Generated by Ledgerium AI'];
  if (meta?.stepCount !== undefined) {
    parts.push(`${meta.stepCount} evidence-linked steps`);
  }
  if (meta?.confidence !== undefined) {
    parts.push(`${Math.round(meta.confidence * 100)}% confidence`);
  }
  if (meta?.generatedAt) {
    parts.push(`Source session: ${meta.generatedAt}`);
  }
  return [
    '',
    '---',
    '',
    `*${parts.join(' · ')}*`,
  ].join('\n');
}

// ─── Process map Markdown dispatchers ────────────────────────────────────────

export function renderProcessMapMarkdown(map: RenderedProcessMap): string {
  switch (map.templateType) {
    case 'swimlane':         return renderSwimlaneMarkdown(map);
    case 'bpmn_informed':    return renderBPMNMarkdown(map);
    case 'sipoc_high_level': return renderSIPOCMarkdown(map);
  }
}

// ─── SOP Markdown dispatchers ────────────────────────────────────────────────

export function renderSOPMarkdown(sop: RenderedSOP): string {
  switch (sop.templateType) {
    case 'operator_centric': return renderOperatorMarkdown(sop);
    case 'enterprise':       return renderEnterpriseMarkdown(sop);
    case 'decision_based':   return renderDecisionMarkdown(sop);
  }
}

// ─── Swimlane Process Map ────────────────────────────────────────────────────

function renderSwimlaneMarkdown(map: SwimlaneProcessMap): string {
  const lines: string[] = [];

  lines.push(mdHeading(1, map.title));
  lines.push('');
  lines.push(`${mdBold('Objective:')} ${map.objective}`);
  lines.push(`${mdBold('Trigger:')} ${map.trigger}`);
  lines.push(`${mdBold('Outcome:')} ${map.outcome}`);
  lines.push(`${mdBold('Duration:')} ${map.durationLabel}`);
  lines.push('');

  // Lanes summary
  lines.push(mdHeading(2, 'Process Lanes'));
  lines.push('');
  lines.push(mdTable(
    ['Lane', 'System', 'Steps'],
    map.lanes.map(l => [l.label, l.system, String(l.stepCount)]),
  ));
  lines.push('');

  // Process flow by lane
  lines.push(mdHeading(2, 'Process Flow'));
  lines.push('');

  for (const lane of map.lanes) {
    const laneSteps = map.steps.filter(s => s.laneId === lane.id);
    if (laneSteps.length === 0) continue;

    lines.push(mdHeading(3, `${lane.label}`));
    lines.push('');
    for (const step of laneSteps) {
      const prefix = step.isExceptionPath ? '⚠ ' : '';
      lines.push(mdNumbered(step.ordinal, `${prefix}${mdBold(step.title)} — ${step.dominantAction}${step.durationLabel ? ` (${step.durationLabel})` : ''}`));

      // Insert decision if one follows this step
      const decision = map.decisions.find(d => d.afterStepOrdinal === step.ordinal);
      if (decision) {
        lines.push(`   ${mdBold('Decision:')} ${decision.label}`);
        lines.push(`   - Yes → ${decision.yesPath}`);
        lines.push(`   - No → ${decision.noPath}`);
      }
    }
    lines.push('');
  }

  // Handoffs
  if (map.handoffs.length > 0) {
    lines.push(mdHeading(2, 'Handoffs'));
    lines.push('');
    for (const h of map.handoffs) {
      lines.push(mdBullet(`Step ${h.fromStepOrdinal} → Step ${h.toStepOrdinal}: ${h.fromLane} → ${h.toLane}`));
    }
    lines.push('');
  }

  // Friction
  if (map.frictionAnnotations.length > 0) {
    lines.push(mdHeading(2, 'Observed Friction'));
    lines.push('');
    for (const f of map.frictionAnnotations) {
      lines.push(mdBullet(`${mdBold(f.severity.toUpperCase())} — ${f.label}`));
    }
    lines.push('');
  }

  // Metadata
  lines.push('---');
  lines.push(`Systems: ${map.metadata.systems.join(', ')} · Steps: ${map.metadata.stepCount} · Phases: ${map.metadata.phaseCount} · Confidence: ${Math.round(map.metadata.confidence * 100)}%`);

  return lines.join('\n');
}

// ─── BPMN-Informed Process Map ───────────────────────────────────────────────

function renderBPMNMarkdown(map: BPMNProcessMap): string {
  const lines: string[] = [];

  lines.push(mdHeading(1, `${map.processName} — BPMN Process Map`));
  lines.push('');
  lines.push(`${mdBold('Process ID:')} ${map.processId}`);
  lines.push(`${mdBold('Start:')} ${map.startEvent.label}`);
  lines.push(`${mdBold('End:')} ${map.endEvent.label}`);
  lines.push('');

  // Pools
  if (map.pools.length > 0) {
    lines.push(mdHeading(2, 'Pools / Lanes'));
    lines.push('');
    lines.push(mdTable(
      ['Pool', 'System', 'Tasks'],
      map.pools.map(p => [p.label, p.system, String(p.taskIds.length)]),
    ));
    lines.push('');
  }

  // Task flow
  lines.push(mdHeading(2, 'Task Flow'));
  lines.push('');
  for (const task of map.tasks) {
    const typeIcon = task.type === 'system' ? '⚙' : task.type === 'manual' ? '⚠' : '👤';
    lines.push(mdNumbered(task.ordinal, `${typeIcon} ${mdBold(task.label)} [${task.type}] — ${task.durationLabel}`));

    // Gateway after this task
    const gateway = map.gateways.find(g => g.afterTaskId === task.id);
    if (gateway) {
      lines.push(`   ${mdBold(`◇ ${gateway.type.toUpperCase()} GATEWAY:`)} ${gateway.label}`);
      for (const cond of gateway.conditions) {
        lines.push(`   → ${cond.label}`);
      }
    }
  }
  lines.push('');

  // System interactions
  if (map.systemInteractions.length > 0) {
    lines.push(mdHeading(2, 'System Interactions'));
    lines.push('');
    for (const si of map.systemInteractions) {
      lines.push(mdBullet(`[${si.type.toUpperCase()}] ${si.system}: ${si.description}`));
    }
    lines.push('');
  }

  // Exception flows
  if (map.exceptionFlows.length > 0) {
    lines.push(mdHeading(2, 'Exception Flows'));
    lines.push('');
    for (const ef of map.exceptionFlows) {
      lines.push(mdBold(ef.errorLabel));
      for (const step of ef.handlingSteps) {
        lines.push(mdBullet(step));
      }
      lines.push(`Resolution: ${ef.resolution}`);
      lines.push('');
    }
  }

  // Metadata
  lines.push('---');
  const flags = [
    map.metadata.hasRetries && 'Retries detected',
    map.metadata.hasSystemEvents && 'System interactions',
    map.metadata.hasParallelPaths && 'Parallel paths',
  ].filter(Boolean).join(' · ');
  lines.push(`Systems: ${map.metadata.systems.join(', ')} · Events: ${map.metadata.eventCount}${flags ? ` · ${flags}` : ''}`);

  return lines.join('\n');
}

// ─── SIPOC + High-Level Process Map ──────────────────────────────────────────

function renderSIPOCMarkdown(map: SIPOCProcessMap): string {
  const lines: string[] = [];

  lines.push(mdHeading(1, map.processName));
  lines.push('');
  lines.push(mdCallout('Business Objective', map.businessObjective));
  lines.push('');

  // SIPOC table
  lines.push(mdHeading(2, 'SIPOC Overview'));
  lines.push('');
  lines.push(mdTable(
    ['Suppliers', 'Inputs', 'Process', 'Outputs', 'Customers'],
    [sipocRow(map)],
  ));
  lines.push('');

  // Process stages
  lines.push(mdHeading(2, 'Process Stages'));
  lines.push('');
  for (const stage of map.processStages) {
    lines.push(mdNumbered(stage.ordinal, `${mdBold(stage.title)} — ${stage.description}`));
  }
  lines.push('');

  // Boundaries
  lines.push(mdHeading(2, 'Process Boundaries'));
  lines.push('');
  lines.push(`${mdBold('Start:')} ${map.boundaries.start}`);
  lines.push(`${mdBold('End:')} ${map.boundaries.end}`);
  lines.push('');

  // Key info
  lines.push(mdHeading(2, 'Key Information'));
  lines.push('');
  lines.push(`${mdBold('Systems:')} ${map.keySystems.join(', ')}`);
  lines.push(`${mdBold('Roles:')} ${map.keyRoles.join(', ')}`);
  lines.push(`${mdBold('Steps:')} ${map.metrics.stepCount} · ${mdBold('Duration:')} ${map.metrics.estimatedDuration} · ${mdBold('Confidence:')} ${Math.round(map.metrics.confidence * 100)}%`);
  lines.push('');

  // Risks
  if (map.riskHighlights.length > 0) {
    lines.push(mdHeading(2, 'Risk Highlights'));
    lines.push('');
    for (const risk of map.riskHighlights) {
      lines.push(mdBullet(risk));
    }
  }

  return lines.join('\n');
}

function sipocRow(map: SIPOCProcessMap): string[] {
  return [
    map.suppliers.slice(0, 3).join(', '),
    map.inputs.slice(0, 3).join(', '),
    map.processStages.map(s => s.title).slice(0, 3).join(' → '),
    map.outputs.slice(0, 3).join(', '),
    map.customers.slice(0, 3).join(', '),
  ];
}

// ─── Operator-Centric SOP ────────────────────────────────────────────────────

function renderOperatorMarkdown(sop: OperatorSOP): string {
  const lines: string[] = [];

  lines.push(mdHeading(1, sop.taskTitle));
  lines.push('');

  // What & When
  lines.push(mdHeading(2, 'What This Is For'));
  lines.push(sop.whatThisIsFor);
  lines.push('');

  lines.push(mdHeading(2, 'When To Use It'));
  lines.push(sop.whenToUseIt);
  lines.push('');

  // Before you begin
  lines.push(mdHeading(2, 'Before You Begin'));
  for (const item of sop.beforeYouBegin) {
    lines.push(mdBullet(item));
  }
  lines.push('');

  // Systems
  if (sop.systemsNeeded.length > 0) {
    lines.push(mdHeading(2, 'Systems Needed'));
    for (const sys of sop.systemsNeeded) {
      lines.push(mdBullet(sys));
    }
    lines.push('');
  }

  // Steps
  lines.push(mdHeading(2, 'Step-by-Step Instructions'));
  lines.push('');
  for (const step of sop.steps) {
    lines.push(mdNumbered(step.number, mdBold(step.action)));
    if (step.detail && step.detail !== step.action) {
      lines.push(`   ${step.detail}`);
    }
    if (step.system) {
      lines.push(`   Performed in ${step.system}`);
    }
    if (step.expectedResult) {
      lines.push(`   ✓ Expected: ${step.expectedResult}`);
    }
    if (step.caution) {
      lines.push(`   ⚠ ${step.caution}`);
    }
    lines.push('');
  }

  // Common mistakes
  if (sop.commonMistakes.length > 0) {
    lines.push(mdHeading(2, 'Common Mistakes'));
    for (const m of sop.commonMistakes) {
      lines.push(mdBullet(m));
    }
    lines.push('');
  }

  // Tips
  if (sop.tips.length > 0) {
    lines.push(mdHeading(2, 'Tips'));
    for (const t of sop.tips) {
      lines.push(mdBullet(t));
    }
    lines.push('');
  }

  // Completion
  lines.push(mdHeading(2, 'Completion Check'));
  for (const c of sop.completionCheck) {
    lines.push(mdBullet(`✓ ${c}`));
  }
  lines.push('');

  lines.push(documentFooter({ stepCount: sop.steps.length }));

  return lines.join('\n');
}

// ─── Enterprise SOP ──────────────────────────────────────────────────────────

function renderEnterpriseMarkdown(sop: EnterpriseSOP): string {
  const lines: string[] = [];

  lines.push(mdHeading(1, sop.title));
  lines.push('');
  lines.push(`${mdBold('SOP ID:')} ${sop.sopId} · ${mdBold('Version:')} ${sop.version}`);
  lines.push('');

  // Purpose & Scope
  lines.push(mdHeading(2, 'Purpose'));
  lines.push(sop.purpose);
  lines.push('');

  lines.push(mdHeading(2, 'Scope'));
  lines.push(sop.scope);
  lines.push('');

  lines.push(mdHeading(2, 'Trigger'));
  lines.push(sop.trigger);
  lines.push('');

  // Roles
  lines.push(mdHeading(2, 'Roles & Responsibilities'));
  lines.push('');
  lines.push(mdTable(
    ['Role', 'Responsibility'],
    sop.rolesAndResponsibilities.map(r => [r.role, r.responsibility]),
  ));
  lines.push('');

  // Prerequisites
  lines.push(mdHeading(2, 'Prerequisites'));
  for (const p of sop.prerequisites) {
    lines.push(mdBullet(p));
  }
  lines.push('');

  // Systems
  lines.push(mdHeading(2, 'Systems & Tools'));
  for (const s of sop.systemsAndTools) {
    lines.push(mdBullet(s));
  }
  lines.push('');

  // Inputs
  if (sop.inputs.length > 0) {
    lines.push(mdHeading(2, 'Inputs'));
    for (const input of sop.inputs) {
      lines.push(mdBullet(input));
    }
    lines.push('');
  }

  // Procedure
  lines.push(mdHeading(2, 'Procedure'));
  lines.push('');
  for (const step of sop.procedure) {
    lines.push(mdHeading(3, `Step ${step.ordinal}: ${step.title}`));
    lines.push('');
    lines.push(`${mdBold('Actor:')} ${step.actor}`);
    if (step.system) lines.push(`${mdBold('System:')} Performed in ${step.system}`);
    lines.push('');
    lines.push(step.instruction);
    lines.push('');
    if (step.inputs.length > 0) {
      lines.push(`${mdBold('Inputs:')} ${step.inputs.map(i => `${i} (required field)`).join(', ')}`);
    }
    if (step.outputs.length > 0) {
      lines.push(`${mdBold('Outputs:')} ${step.outputs.join(', ')}`);
    }
    lines.push(`${mdBold('Verification:')} ${step.verificationPoint}`);
    lines.push('');
  }

  // Decision points
  if (sop.decisionPoints.length > 0) {
    lines.push(mdHeading(2, 'Decision Points'));
    lines.push('');
    for (const dp of sop.decisionPoints) {
      lines.push(`${mdBold(`At Step ${dp.atStepOrdinal}:`)} ${dp.question}`);
      for (const opt of dp.options) {
        lines.push(mdBullet(`${mdBold(opt.condition)}: ${opt.action}`));
      }
      lines.push('');
    }
  }

  // Controls
  lines.push(mdHeading(2, 'Controls & Checkpoints'));
  for (const c of sop.controls) {
    lines.push(mdBullet(c));
  }
  lines.push('');

  // Risks
  lines.push(mdHeading(2, 'Risks & Cautions'));
  for (const r of sop.risks) {
    lines.push(mdBullet(r));
  }
  lines.push('');

  // Outputs
  lines.push(mdHeading(2, 'Outputs'));
  for (const o of sop.outputs) {
    lines.push(mdBullet(o));
  }
  lines.push('');

  // Completion
  lines.push(mdHeading(2, 'Completion Criteria'));
  for (const c of sop.completionCriteria) {
    lines.push(mdBullet(`✓ ${c}`));
  }
  lines.push('');

  // Revision metadata
  lines.push('---');
  lines.push(`*${sop.sourceNote}*`);
  lines.push('');
  lines.push(`Generated: ${sop.revisionMetadata.generatedAt} · Engine: ${sop.revisionMetadata.engineVersion} · Source: ${sop.revisionMetadata.basedOn}`);

  return lines.join('\n');
}

// ─── Decision-Based SOP ──────────────────────────────────────────────────────

function renderDecisionMarkdown(sop: DecisionSOP): string {
  const lines: string[] = [];

  lines.push(mdHeading(1, sop.title));
  lines.push('');

  lines.push(mdHeading(2, 'Purpose'));
  lines.push(sop.purpose);
  lines.push('');

  lines.push(mdHeading(2, 'Trigger Condition'));
  lines.push(sop.triggerCondition);
  lines.push('');

  // Inputs
  lines.push(mdHeading(2, 'Inputs / Context Needed'));
  for (const input of sop.inputsNeeded) {
    lines.push(mdBullet(input));
  }
  lines.push('');

  // Initial assessment
  lines.push(mdHeading(2, 'Initial Assessment'));
  lines.push(sop.initialAssessment);
  lines.push('');

  // Branches
  lines.push(mdHeading(2, 'Decision Paths'));
  lines.push('');
  for (let i = 0; i < sop.branches.length; i++) {
    const branch = sop.branches[i]!;
    lines.push(mdHeading(3, `Path ${i + 1}: ${branch.condition}`));
    lines.push('');
    for (const action of branch.actions) {
      lines.push(mdNumbered(action.ordinal, action.instruction));
      if (action.system) {
        lines.push(`   Performed in ${action.system}`);
      }
    }
    lines.push('');
    lines.push(mdCallout('Outcome', branch.outcome));
    lines.push('');
  }

  // Escalation
  lines.push(mdHeading(2, 'Escalation Rules'));
  for (const rule of sop.escalationRules) {
    lines.push(mdBullet(rule));
  }
  lines.push('');

  // Exception handling
  lines.push(mdHeading(2, 'Exception Handling'));
  for (const ex of sop.exceptionHandling) {
    lines.push(mdBullet(ex));
  }
  lines.push('');

  // Resolution outcomes
  lines.push(mdHeading(2, 'Resolution Outcomes'));
  for (const r of sop.resolutionOutcomes) {
    lines.push(mdBullet(`✓ ${r}`));
  }
  lines.push('');

  // Completion
  lines.push(mdHeading(2, 'Completion Criteria'));
  for (const c of sop.completionCriteria) {
    lines.push(mdBullet(`✓ ${c}`));
  }
  lines.push('');

  // Documentation requirements
  lines.push(mdHeading(2, 'Documentation Requirements'));
  for (const doc of sop.documentationRequirements) {
    lines.push(mdBullet(doc));
  }
  lines.push('');

  lines.push(documentFooter({ stepCount: sop.branches.reduce((acc, b) => acc + b.actions.length, 0) }));

  return lines.join('\n');
}
