/**
 * sopValidator tests — verifies all quality-gate rules against inline fixtures.
 *
 * Fixtures are constructed directly without running processSession so each
 * rule is isolated and deterministic.  Pattern follows templates.test.ts.
 */

import { describe, it, expect } from 'vitest';
import { validateRenderedSOP } from './sopValidator.js';
import type { SOPValidation } from './sopValidator.js';
import type { RenderedSOP, OperatorSOP, OperatorSOPStep } from '../templateTypes.js';
import type { ProcessOutput, SOPStep, SOPInstruction } from '../types.js';

// ─── Fixture helpers ─────────────────────────────────────────────────────────

/**
 * A minimal SOPInstruction (evidence event) for a step.
 */
function instruction(overrides?: Partial<SOPInstruction>): SOPInstruction {
  return {
    sequence: 1,
    instruction: 'Click the Save button',
    eventType: 'interaction.click',
    sourceEventId: 'evt-1',
    isSensitive: false,
    redacted: false,
    ...overrides,
  };
}

/**
 * A minimal SOPStep with one instruction and a non-empty expectedOutcome.
 */
function sopStep(overrides?: Partial<SOPStep>): SOPStep {
  return {
    ordinal: 1,
    stepId: 'step-1',
    title: 'Save the record',
    category: 'single_action',
    action: 'Click Save',
    instructions: [instruction()],
    detail: '1. Click the Save button',
    inputs: [],
    expectedOutcome: 'Record is saved successfully',
    warnings: [],
    durationLabel: '< 1 s',
    confidence: 0.9,
    sourceStepId: 'step-1',
    ...overrides,
  };
}

/**
 * A minimal OperatorSOPStep used inside RenderedSOP fixtures.
 */
function operatorSOPStep(overrides?: Partial<OperatorSOPStep>): OperatorSOPStep {
  return {
    number: 1,
    action: 'Click Save',
    detail: 'Click the Save button',
    system: 'TestApp',
    expectedResult: 'Record is saved',
    caution: '',
    ...overrides,
  };
}

/**
 * A valid minimal OperatorSOP — passes all rules.
 * Uses a meaningful title and purpose, 3 steps.
 */
function validRenderedSOP(overrides?: Partial<OperatorSOP>): OperatorSOP {
  const steps: OperatorSOPStep[] = [
    operatorSOPStep({ number: 1, action: 'Open the invoice form' }),
    operatorSOPStep({ number: 2, action: 'Enter vendor and amount' }),
    operatorSOPStep({ number: 3, action: 'Submit the invoice' }),
  ];
  return {
    templateType: 'operator_centric',
    taskTitle: 'Q2 invoice intake',
    whatThisIsFor: 'Turn a recorded workflow into a shareable SOP so the team has one source of truth.',
    whenToUseIt: 'When processing a new invoice in SAP.',
    beforeYouBegin: ['Access to SAP', 'Invoice PDF ready'],
    systemsNeeded: ['SAP'],
    steps,
    commonMistakes: [],
    tips: ['Double-check the vendor code'],
    completionCheck: ['Invoice is in Submitted status'],
    sourceNote: 'Generated by Ledgerium AI',
    ...overrides,
  };
}

/**
 * A minimal ProcessOutput with a valid SOP (3 steps, each with instructions
 * and a non-empty expectedOutcome).
 */
function validOutput(stepOverrides?: Partial<SOPStep>[]): ProcessOutput {
  const steps: SOPStep[] = stepOverrides
    ? stepOverrides.map((o, i) => sopStep({ ordinal: i + 1, stepId: `step-${i + 1}`, ...o }))
    : [
        sopStep({ ordinal: 1, stepId: 'step-1', title: 'Open invoice form' }),
        sopStep({ ordinal: 2, stepId: 'step-2', title: 'Enter data' }),
        sopStep({ ordinal: 3, stepId: 'step-3', title: 'Submit invoice' }),
      ];

  return {
    processRun: {
      runId: 'run-1',
      sessionId: 'sess-1',
      activityName: 'Q2 invoice intake',
      startedAt: '2026-01-01T00:00:00Z',
      durationLabel: '< 1 min',
      stepCount: steps.length,
      eventCount: steps.length,
      humanEventCount: steps.length,
      systemEventCount: 0,
      systemsUsed: ['TestApp'],
      errorStepCount: 0,
      navigationStepCount: 0,
      completionStatus: 'complete',
      engineVersion: '1.2.0',
    },
    processDefinition: {
      definitionId: 'def-1',
      name: 'Q2 invoice intake',
      version: '1.0',
      description: 'Invoice intake process',
      purpose: 'Process invoices',
      scope: 'Finance team',
      systems: ['TestApp'],
      domains: ['testapp.example.com'],
      estimatedDurationLabel: '< 1 min',
      stepDefinitions: [],
      ruleVersion: '1.0',
    },
    processMap: {
      id: 'map-1',
      name: 'Q2 invoice intake',
      version: '1.0',
      sessionId: 'sess-1',
      systems: ['TestApp'],
      phases: [],
      nodes: [],
      edges: [],
    },
    sop: {
      sopId: 'sop-1',
      title: 'Q2 invoice intake',
      version: '1.0',
      purpose: 'Process invoices efficiently.',
      scope: 'Finance team',
      systems: ['TestApp'],
      prerequisites: [],
      estimatedTime: '< 1 min',
      inputs: [],
      outputs: [],
      completionCriteria: ['Invoice submitted'],
      steps,
      notes: [],
      generatedAt: '2026-01-01T00:00:00Z',
    },
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════════════════

describe('validateRenderedSOP — passes valid SOP', () => {
  it('returns ok: true for a 3-step SOP with all rules satisfied', () => {
    const result = validateRenderedSOP(validRenderedSOP(), validOutput());
    expect(result.ok).toBe(true);
  });
});

// ─── Rule 1: banned recorder artifacts ───────────────────────────────────────

describe('validateRenderedSOP — Rule 1: banned_recorder_artifact', () => {
  const BANNED_CASES: Array<{ label: string; banned: string }> = [
    { label: 'Click the div',          banned: 'Click the div' },
    { label: 'Click the span',         banned: 'Click the span' },
    { label: 'Click the svg',          banned: 'Click the svg' },
    { label: 'Click the p',            banned: 'Click the p' },
    { label: 'Click the li',           banned: 'Click the li' },
    { label: 'Click the section',      banned: 'Click the section' },
    { label: 'Interact with element',  banned: 'Interact with element' },
    { label: 'Perform action',         banned: 'Perform action' },
  ];

  for (const { label, banned } of BANNED_CASES) {
    it(`rejects "${label}" in rendered markdown`, () => {
      // Inject the banned string into the step action so it appears in rendered Markdown.
      const rendered = validRenderedSOP({
        steps: [
          operatorSOPStep({ number: 1, action: banned }),
          operatorSOPStep({ number: 2, action: 'Enter data' }),
          operatorSOPStep({ number: 3, action: 'Submit form' }),
        ],
      });
      const result = validateRenderedSOP(rendered, validOutput());

      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.reason).toBe('banned_recorder_artifact');
        expect(result.diagnostic).toContain(banned);
        expect(result.suggestion.length).toBeGreaterThan(0);
      }
    });
  }

  it('returns structured { ok, reason, diagnostic, suggestion } with all fields non-empty', () => {
    const rendered = validRenderedSOP({
      steps: [
        operatorSOPStep({ number: 1, action: 'Click the div' }),
        operatorSOPStep({ number: 2, action: 'Enter data' }),
      ],
    });
    const result: SOPValidation = validateRenderedSOP(rendered, validOutput());

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(typeof result.reason).toBe('string');
      expect(result.reason.length).toBeGreaterThan(0);
      expect(typeof result.diagnostic).toBe('string');
      expect(result.diagnostic.length).toBeGreaterThan(0);
      expect(typeof result.suggestion).toBe('string');
      expect(result.suggestion.length).toBeGreaterThan(0);
    }
  });
});

// ─── Rule 2: too_few_steps ────────────────────────────────────────────────────

describe('validateRenderedSOP — Rule 2: too_few_steps', () => {
  it('rejects when output.sop.steps.length === 1', () => {
    const output = validOutput([{ ordinal: 1, stepId: 'step-1', title: 'Only step' }]);
    const result = validateRenderedSOP(validRenderedSOP(), output);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe('too_few_steps');
      expect(result.diagnostic).toContain('1 step(s)');
      expect(result.suggestion.length).toBeGreaterThan(0);
    }
  });

  it('rejects when output.sop.steps.length === 0', () => {
    const output = validOutput([]);
    const result = validateRenderedSOP(validRenderedSOP(), output);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe('too_few_steps');
      expect(result.diagnostic).toContain('0 step(s)');
    }
  });

  it('returns structured error with all fields non-empty', () => {
    const output = validOutput([{ ordinal: 1, stepId: 'step-1', title: 'Only step' }]);
    const result: SOPValidation = validateRenderedSOP(validRenderedSOP(), output);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason.length).toBeGreaterThan(0);
      expect(result.diagnostic.length).toBeGreaterThan(0);
      expect(result.suggestion.length).toBeGreaterThan(0);
    }
  });
});

// ─── Rule 3: step_has_no_evidence ────────────────────────────────────────────

describe('validateRenderedSOP — Rule 3: step_has_no_evidence', () => {
  it('rejects when one step has instructions: []', () => {
    const output = validOutput([
      { ordinal: 1, stepId: 'step-1', title: 'Open form' },
      { ordinal: 2, stepId: 'step-2', title: 'Empty step', instructions: [] },
      { ordinal: 3, stepId: 'step-3', title: 'Submit' },
    ]);
    const result = validateRenderedSOP(validRenderedSOP(), output);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe('step_has_no_evidence');
      expect(result.diagnostic).toContain('Step 2');
      expect(result.suggestion.length).toBeGreaterThan(0);
    }
  });

  it('returns structured error with all fields non-empty', () => {
    const output = validOutput([
      { ordinal: 1, stepId: 'step-1', title: 'Open form' },
      { ordinal: 2, stepId: 'step-2', title: 'Empty step', instructions: [] },
    ]);

    // Step count is still 2 (passes Rule 2), so Rule 3 is reached.
    const result: SOPValidation = validateRenderedSOP(validRenderedSOP(), output);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason.length).toBeGreaterThan(0);
      expect(result.diagnostic.length).toBeGreaterThan(0);
      expect(result.suggestion.length).toBeGreaterThan(0);
    }
  });
});

// ─── Rule 4: empty_expected_outcomes ─────────────────────────────────────────

describe('validateRenderedSOP — Rule 4: empty_expected_outcomes', () => {
  it('rejects when one step has expectedOutcome: ""', () => {
    const output = validOutput([
      { ordinal: 1, stepId: 'step-1', title: 'Open form' },
      { ordinal: 2, stepId: 'step-2', title: 'Submit', expectedOutcome: '' },
      { ordinal: 3, stepId: 'step-3', title: 'Confirm' },
    ]);
    const result = validateRenderedSOP(validRenderedSOP(), output);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe('empty_expected_outcomes');
      expect(result.diagnostic).toContain('1 step(s)');
      expect(result.suggestion.length).toBeGreaterThan(0);
    }
  });

  it('returns structured error with all fields non-empty', () => {
    const output = validOutput([
      { ordinal: 1, stepId: 'step-1', title: 'Open form' },
      { ordinal: 2, stepId: 'step-2', title: 'Submit', expectedOutcome: '' },
      { ordinal: 3, stepId: 'step-3', title: 'Confirm' },
    ]);
    const result: SOPValidation = validateRenderedSOP(validRenderedSOP(), output);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason.length).toBeGreaterThan(0);
      expect(result.diagnostic.length).toBeGreaterThan(0);
      expect(result.suggestion.length).toBeGreaterThan(0);
    }
  });
});

// ─── Rule 5 (bonus): generic_title ───────────────────────────────────────────

describe('validateRenderedSOP — Rule 5: generic_title', () => {
  const GENERIC_TITLES = [
    'Workflow 1',
    'Untitled Process',
    'workflow',
    'Untitled Workflow 42',
    'Workflow',
    'WORKFLOW 12',
  ];

  for (const title of GENERIC_TITLES) {
    it(`rejects generic title "${title}"`, () => {
      const rendered = validRenderedSOP({ taskTitle: title });
      const result = validateRenderedSOP(rendered, validOutput());

      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.reason).toBe('generic_title');
        expect(result.diagnostic).toContain(title);
        expect(result.suggestion.length).toBeGreaterThan(0);
      }
    });
  }

  const ACCEPTABLE_TITLES = [
    'Q2 invoice intake',
    'Upload and Review Workflow',
    'Process payroll for November',
    'SAP Invoice Submission',
  ];

  for (const title of ACCEPTABLE_TITLES) {
    it(`accepts meaningful title "${title}"`, () => {
      const rendered = validRenderedSOP({ taskTitle: title });
      const result = validateRenderedSOP(rendered, validOutput());
      // Should not fail on generic_title (may pass or fail on another rule)
      if (!result.ok) {
        expect(result.reason).not.toBe('generic_title');
      }
    });
  }
});

// ─── Rule 6 (bonus): prose_only_purpose ──────────────────────────────────────

describe('validateRenderedSOP — Rule 6: prose_only_purpose', () => {
  it('rejects when whatThisIsFor starts with "This SOP describes "', () => {
    const rendered = validRenderedSOP({
      whatThisIsFor: 'This SOP describes the procedure for uploading workflow files.',
    });
    const result = validateRenderedSOP(rendered, validOutput());

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe('prose_only_purpose');
      expect(result.diagnostic.length).toBeGreaterThan(0);
      expect(result.suggestion.length).toBeGreaterThan(0);
    }
  });

  it('is case-insensitive for the prose prefix', () => {
    const rendered = validRenderedSOP({
      whatThisIsFor: 'this sop describes how to upload invoices.',
    });
    const result = validateRenderedSOP(rendered, validOutput());

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe('prose_only_purpose');
    }
  });

  it('returns structured error with all fields non-empty', () => {
    const rendered = validRenderedSOP({
      whatThisIsFor: 'This SOP describes the invoice process.',
    });
    const result: SOPValidation = validateRenderedSOP(rendered, validOutput());

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason.length).toBeGreaterThan(0);
      expect(result.diagnostic.length).toBeGreaterThan(0);
      expect(result.suggestion.length).toBeGreaterThan(0);
    }
  });
});

// ─── Rule ordering: first-match wins ─────────────────────────────────────────

describe('validateRenderedSOP — rule ordering', () => {
  it('banned_recorder_artifact wins when both banned artifact AND too_few_steps apply', () => {
    // 1 step (fails Rule 2) + banned string in action (fails Rule 1)
    const rendered = validRenderedSOP({
      steps: [operatorSOPStep({ number: 1, action: 'Click the div' })],
    });
    // Only 1 step in output.sop.steps — would also trigger too_few_steps
    const output = validOutput([{ ordinal: 1, stepId: 'step-1', title: 'Single step' }]);

    const result = validateRenderedSOP(rendered, output);

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe('banned_recorder_artifact');
    }
  });
});
