import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { db } from '@/db';
import { renderProcessMapMarkdown, renderSOPMarkdown } from '@ledgerium/process-engine';
import { hasFeature } from '@/lib/plans';
import { effectivePlanFor } from '@/lib/feature-gating';
import { LATEST_ARTIFACT_ORDER_BY } from '@/lib/artifacts';

const FREE_PLAN_WATERMARK_PREPEND =
  '> *Generated by [Ledgerium AI](https://ledgerium.ai) — Free Plan. Upgrade for clean exports.*\n\n---\n\n';

const FREE_PLAN_WATERMARK_APPEND =
  '\n\n---\n\n> *This document was generated by Ledgerium AI (Free Plan). [Upgrade](https://ledgerium.ai/pricing) to remove this watermark.*';

/**
 * GET /api/workflows/[id]/export-markdown?artifactType=template_sop_enterprise
 *
 * Renders a stored template artifact to Markdown and returns it as a download.
 */
export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } },
) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Effective plan for export watermarking (reverse trial + workspace). The raw
  // `plan` column watermarked exports for trial users whose Solo grant
  // includes cleanExports.
  const plan = await effectivePlanFor(session.user.id);
  const isCleanExport = hasFeature(plan, 'cleanExports');

  const artifactType = req.nextUrl.searchParams.get('artifactType');
  if (!artifactType || !artifactType.startsWith('template_')) {
    return NextResponse.json({ error: 'artifactType query parameter required' }, { status: 400 });
  }

  // Verify workflow ownership
  const workflow = await db.workflow.findFirst({
    where: { id: params.id, userId: session.user.id },
    select: { id: true, title: true },
  });
  if (!workflow) {
    return NextResponse.json({ error: 'Workflow not found' }, { status: 404 });
  }

  // Find the template artifact. B-3: multiple rows of this artifactType can
  // exist (append-only regeneration) — order deterministically and take the
  // newest so repeated exports of the same workflow are byte-identical.
  const artifact = await db.workflowArtifact.findFirst({
    where: { workflowId: params.id, artifactType },
    orderBy: LATEST_ARTIFACT_ORDER_BY,
  });
  if (!artifact?.contentJson) {
    return NextResponse.json({ error: 'Template artifact not found' }, { status: 404 });
  }

  const content = JSON.parse(artifact.contentJson);
  let markdown: string;

  if (artifactType.startsWith('template_process_map_')) {
    markdown = renderProcessMapMarkdown(content);
  } else if (artifactType.startsWith('template_sop_')) {
    markdown = renderSOPMarkdown(content);
  } else {
    return NextResponse.json({ error: 'Unsupported artifact type' }, { status: 400 });
  }

  // Apply watermark for Free plan users who lack the cleanExports feature
  if (!isCleanExport) {
    markdown = FREE_PLAN_WATERMARK_PREPEND + markdown + FREE_PLAN_WATERMARK_APPEND;
  }

  const slug = workflow.title.replace(/\s+/g, '-').toLowerCase();
  const templateName = artifactType.replace('template_process_map_', '').replace('template_sop_', '');
  const filename = `${slug}-${templateName}.md`;

  return new NextResponse(markdown, {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  });
}
